Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('payment')->group(function() {
            Route::name('payment.')->group(function() {

                Route::get('dashboard', 'Admin\PaymentController@index')->name('dashboard');//->middleware('permission:ecommerce-dashboard-read');

                // Route::prefix('product')->group(function() {

                //     Route::prefix('product')->group(function() {
                //         Route::name('product.')->group(function() {
                //             Route::get('/', 'Admin\ProductController@index')->name('index');
                //         });
                //     });

                // });

            });
        });
    });
});

Entities/PaymentModel.php
<?php

namespace Modules\Payment\Entities;

use App\Models\BaseModel;

class PaymentModel extends BaseModel
{
    public const DB_TABLE_PREFIX = 'paym_';
}

Http/Controllers/Admin/PaymentController.php
<?php

namespace Modules\Payment\Http\Controllers\Admin;

use Illuminate\Routing\Controller;

class PaymentController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Payment Module';
    }
    
    public function index()
    {
        $params['pageTitle'] = $this->pageTitle;
        return view('payment::admin.index', $params);
    }
}

Resources/views/admin/index.blade.php
@extends('payment::layouts.master')

@section('content')

    <p>
        This view is loaded from module: {!! config('payment.name') !!}
    </p>
@endsection

Resources/views/admin/shared/sidebar.blade.php
{{-- @can('payment') --}}
<li class="treeview @if($adminActiveMenu == 'payment') active @endif">
    <a href="#">
        <i class="fa fa-money"></i>
        <span>Payment</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            <span class="label label-danger pull-right">
                New
            </span>
        </span>
    </a>
    <ul class="treeview-menu">
        {{-- @can('payment-dashboard-read') --}}
        <li class="@if($adminActiveSubMenu == 'dashboard') active @endif">
            <a href="{!! route('payment.dashboard') !!}">
                <i class="fa fa-circle-o"></i> Dashboard
                <span class="pull-right-container"></span>
            </a>
        </li>
        {{-- @endcan --}}
        {{-- @can('ecommerce-product')
            <li class="@if($adminActiveSubMenu == 'product') active @endif">
                <a href="#"><i class="fa fa-circle-o"></i> Products
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    @can('product-read')
                        <li class="@if($adminActiveSubMenu == 'product' && $urlSegment4 == 'product') active @endif">
                            <a href="{!! route('ecommerce.product.index') !!}">
                                <i class="fa fa-circle-o"></i> Product List
                                <span class="pull-right-container"></span>
                            </a>
                        </li>
                    @endcan
                    @can('product-category-read')
                        <li class="@if($adminActiveSubMenu == 'product' && $urlSegment4 == 'product-category') active @endif">
                            <a href="{!! route('ecommerce.product-category.index') !!}">
                                <i class="fa fa-circle-o"></i> Product Category
                                <span class="pull-right-container"></span>
                            </a>
                        </li>
                    @endcan
                    @can('product-attribute-read')
                        <li class="@if($adminActiveSubMenu == 'product' && $urlSegment4 == 'product-attribute') active @endif">
                            <a href="{!! route('ecommerce.product-attribute.index') !!}">
                                <i class="fa fa-circle-o"></i> Product Attribute
                                <span class="pull-right-container"></span>
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan --}}
        
    </ul>
</li>
{{-- @endcan --}}

Resources/views/layouts/master.blade.php
@extends('layouts.app')